# Generated by Django 5.0.7 on 2024-07-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='otro',
            field=models.BooleanField(default=True),
        ),
    ]
