# Generated by Django 5.0.7 on 2024-07-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_otro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='otro',
        ),
    ]
